---

output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Title

Quantitative approaches for improved management and conservation of aquatic resources

# Abstract

Our understanding of natural history phenomena has grown remarkably over time, due largely to advances in the ways we collect and analyze data. Remote sensing platforms now allow us to observe systems over larger spatial and temporal extents, with finer resolution, than ever before. Our ability to sequence entire genomes is transforming our views on diseases and evolutionary pathways. Citizen science programs can provide supplemental monitoring of a wide range of plants and animals. Coincident with these improvements in data collection, we have witnessed a rapid expansion of quantitative approaches for identifying processes from patterns. Improvements in statistical models and numerical algorithms, coupled with better software and hardware allow us to extract more meaningful information from our data in less time. These include analyses of individuals (e.g., movement tracking), communities (e.g., inter-species interactions), and landscapes (e.g., joint species distributions). Using examples from Pacific salmon, I will highlight applications of new quantitative tools that have enhanced not only our understanding of past conditions, but also our ability to forecast future outcomes.

# Biosketch

Mark is an applied ecologist at NOAA‘s Northwest Fisheries Science Center and an Affiliate Associate Professor in the School of Aquatic and Fishery Sciences at the University of Washington. He works on a variety of problems related to the conservation and management of aquatic resources, particularly along the west coast of North America. Much of his research is focused on the development and application of statistical methods for analyzing temporal and spatial data. Mark has a B.S. in Zoology from the University of Wisconsisn, an M.S. in Fishery and Aquatic Science from Cornell University, and a Ph.D. in Zoology from the University of Washington.

